# Generated by Django 3.0.3 on 2020-02-12 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('anonymous', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='text time')),
            ],
        ),
    ]
