# Generated by Django 3.0.3 on 2020-02-12 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anonymous', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anonymousclass',
            name='username',
        ),
    ]
