# Generated by Django 3.0.3 on 2020-02-12 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ridikkulus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('university_roll', models.IntegerField()),
                ('image', models.URLField(null=True)),
                ('img', models.ImageField(null=True, upload_to='profilepic/')),
                ('caption', models.CharField(blank=True, max_length=500, null=True)),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='upload time')),
            ],
        ),
    ]
