# Generated by Django 3.0.3 on 2020-02-12 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ridikkulus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ridikkulus',
            name='img',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
